# API Gateway Deployment configuration
appName: api-gateway
replicas: 2
image: api-gateway:latest
imagePullPolicy: Always
containerPort: 5000

volumeMounts:
  - name: sacheduler-config-map
    mountPath: /etc/sacheduler-config-map

# Resource requests and limits
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

# Environment variables from ConfigMap
envFrom:
  - configMapRef:
      name: sacheduler-config-map

# Environment variables from Secrets
env:
  - name: GOOGLE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: GOOGLE_CLIENT_SECRET
  - name: GOOGLE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: GOOGLE_CLIENT_ID
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: JWT_SECRET
  - name: SESSION_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: SESSION_SECRET_KEY

# Pod Anti-Affinity
podAntiAffinity: true

volumes:
  - name: sacheduler-config-map
    configMap:
      name: sacheduler-config-map

# API Gateway Service configuration
app:
  name: api-gateway

service:
  name: api-gateway
  namespace: default
  protocol: TCP
  port: 5050
  targetPort: 5050
  type: ClusterIP