# User Management Deployment configuration
appName: user-management
replicas: 2
image: gcr.io/bold-flash-400821/user-management-6e1ed035@sha256:8d178a7f5357d7d67c6e138df36e60760e98a2f75ce60f3a6adb8268bbd0ed8e
imagePullPolicy: Always
containerPort: 5000

volumeMounts:
  - name: sacheduler-config-map
    mountPath: /etc/sacheduler-config-map

# Resource requests and limits
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

# Environment variables from ConfigMap
envFrom:
  - configMapRef:
      name: sacheduler-config-map

# Environment variables from Secrets
env:
  - name: GOOGLE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: GOOGLE_CLIENT_SECRET
  - name: GOOGLE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: GOOGLE_CLIENT_ID
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: JWT_SECRET
  - name: SESSION_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: placeholder
        key: SESSION_SECRET_KEY

# Pod Anti-Affinity
podAntiAffinity: true

volumes:
  - name: sacheduler-config-map
    configMap:
      name: sacheduler-config-map

# User Management Service configuration
app:
  name: user-management

service:
  name: user-management
  namespace: default
  protocol: TCP
  port: 5000
  targetPort: 5000
  type: ClusterIP
