{{- define "sacheduler.secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  GOOGLE_CLIENT_ID: {{ .Values.googleClientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.googleClientSecret | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  SESSION_SECRET_KEY: {{ .Values.sessionSecretKey | b64enc | quote }}
{{- end -}}